spring:
  application:
    name: authentic-service
  mvc:
    static-path-pattern: /static/**
    thymeleaf:
      cache: false
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/oauth_two?serverTimezone=GMT%2B8&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hcy1805110063
    type: com.alibaba.druid.pool.DruidDataSource
    # 如果没有 druid依赖，则不写下面 druid 的配置
    druid:
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 5000
  mybatis-plus:
    type-aliases-package: com.hcy.pojo
    mapper-locations: classpath:mapper/**.xml
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
server:
  port: 8002